const std = @import("std");

pub const Subvol = struct { name: []const u8, mount_point: []const u8 };

// Mounted by subvol name, never subvolid -- see docs/ARCHITECTURE.md §2:
// `snapper rollback` recreates subvolumes with new IDs.
pub const subvols = [_]Subvol{
    .{ .name = "@", .mount_point = "/" },
    .{ .name = "@home", .mount_point = "/home" },
    .{ .name = "@var_log", .mount_point = "/var/log" },
    .{ .name = "@var_cache", .mount_point = "/var/cache" },
    .{ .name = "@snapshots", .mount_point = "/.snapshots" },
};

pub const Layout = struct {
    root_uuid: []const u8,
    esp_uuid: []const u8,
    compress: []const u8 = "zstd:1",
};

pub fn generate(allocator: std.mem.Allocator, layout: Layout) ![]const u8 {
    var out = std.ArrayList(u8).init(allocator);
    errdefer out.deinit();
    const w = out.writer();

    try w.print("# /etc/fstab: generated by koompi-install\n", .{});
    for (subvols) |sv| {
        try w.print("UUID={s} {s} btrfs subvol={s},compress={s},noatime 0 0\n", .{
            layout.root_uuid, sv.mount_point, sv.name, layout.compress,
        });
    }
    try w.print("UUID={s} /boot/efi vfat umask=0077 0 2\n", .{layout.esp_uuid});

    return out.toOwnedSlice();
}

test "generates one line per subvolume mounted by name, plus the ESP" {
    const allocator = std.testing.allocator;
    const text = try generate(allocator, .{ .root_uuid = "1111-1111", .esp_uuid = "2222-2222" });
    defer allocator.free(text);

    try std.testing.expectEqualStrings(
        \\# /etc/fstab: generated by koompi-install
        \\UUID=1111-1111 / btrfs subvol=@,compress=zstd:1,noatime 0 0
        \\UUID=1111-1111 /home btrfs subvol=@home,compress=zstd:1,noatime 0 0
        \\UUID=1111-1111 /var/log btrfs subvol=@var_log,compress=zstd:1,noatime 0 0
        \\UUID=1111-1111 /var/cache btrfs subvol=@var_cache,compress=zstd:1,noatime 0 0
        \\UUID=1111-1111 /.snapshots btrfs subvol=@snapshots,compress=zstd:1,noatime 0 0
        \\UUID=2222-2222 /boot/efi vfat umask=0077 0 2
        \\
    , text);
}
